name: docs_QCANT
channels:

  - conda-forge

  - defaults
dependencies:
  - python>=3.11,<3.13
  - pip
  - sphinx
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton
  - pip:
    - -e ../
